job_specifications:
- id: tensorflowjob
  tasks:
  - docker_image: gcr.io/tensorflow/tensorflow
    resource_files:
    - blob_source: https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py
      file_path: mnist_with_summaries.py
    command: python -u mnist_with_summaries.py --log_dir=logs --max_steps=5000
