job_specifications:
- id: namdjob
  auto_complete: true
  tasks:
  - image: alfpark/namd:2.11-icc-mkl-intelmpi
    multi_instance:
      num_instances: pool_current_dedicated
    command: /sw/run_namd.sh apoa1 1000
