title: Batch Shipyard
description: Provision, execute, and monitor containerized workloads on Azure Batch
google_analytics:
show_downloads: false
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
