job_specifications:
- id: linpack
  auto_complete: true
  tasks:
  - docker_image: alfpark/linpack:cpu-intel-mkl
    additional_docker_run_options:
    - --privileged
    multi_instance:
      num_instances: pool_current_dedicated
    command: /sw/run_hplinpack.sh -2
