pool_specification:
  id: remotefs-batchpool
  virtual_network:
    name: myvnet
    resource_group: my-resource-group
    address_space: 10.0.0.0/16
    subnet:
      name: batch-nodes
      address_prefix: 10.0.1.0/24
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
  vm_count:
    dedicated: 4
    low_priority: 0
  vm_size: STANDARD_D2_V2
  inter_node_communication_enabled: true
  ssh:
    username: docker
