job_specifications:
- id: hpcg
  auto_complete: true
  tasks:
  - image: alfpark/linpack:cpu-intel-mkl
    multi_instance:
      num_instances: pool_current_dedicated
    command: /sw/run_hpcg.sh -n 256 -t 120
