job_specifications:
- id: mxnetjob
  auto_complete: true
  tasks:
  - docker_image: alfpark/mxnet:cpu
    shared_data_volumes:
    - glustervol
    multi_instance:
      num_instances: pool_current_dedicated
    command: /mxnet/run_mxnet.sh cifar-10-r $AZ_BATCH_NODE_SHARED_DIR/gfs --model-prefix $AZ_BATCH_TASK_WORKING_DIR/cifar-10-model
