job_specifications:
- id: tensorflow
  auto_complete: true
  tasks:
  - image: alfpark/tensorflow:1.2.1-cpu
    multi_instance:
      num_instances: pool_current_dedicated
    command: /bin/bash -c "/shipyard/launcher.sh /shipyard/mnist_replica.py"
