job_specifications:
- id: linpack
  tasks:
  - singularity_image: shub://alfpark/linpack
    additional_singularity_options:
    - --pwd /intel/mkl/benchmarks/mp_linpack
    resource_files:
    - blob_source: https://raw.githubusercontent.com/alfpark/linpack/master/findpq.py
      file_path: findpq.py
    - blob_source: https://raw.githubusercontent.com/alfpark/linpack/master/run_hplinpack.sh
      file_path: run_hplinpack.sh
    command: ./run_hplinpack.sh -2
    multi_instance:
      num_instances: pool_current_dedicated
